import { describe, expect, it } from 'vitest'
import msiValidationSource from '../../scripts/windows-msi/Test-HualiAIMsi.ps1?raw'
import deploymentSmokeSource from '../../scripts/windows-msi/Test-HualiAISilentDeployment.ps1?raw'
import visualSmokeSource from '../../scripts/windows-msi/Test-HualiAIWindowsVisualSmoke.ps1?raw'
import deploymentReadmeSource from '../../scripts/windows-msi/平台部署说明.txt?raw'
import rustSource from '../../src-tauri/src/main.rs?raw'

describe('Windows administrator deployment smoke contracts', () => {
  it('requires the machine-wide desktop authentication callback protocol throughout MSI lifecycle gates', () => {
    const msiValidation = msiValidationSource.replace(/\r\n?/g, '\n')
    const deployment = deploymentSmokeSource.replace(/\r\n?/g, '\n')

    expect(msiValidation).toContain("Software\\Classes\\huali-ai-mascot")
    expect(msiValidation).toContain("-Sql 'SELECT `Root`, `Key`, `Name`, `Value` FROM `Registry`'")
    expect(msiValidation).not.toMatch(/FROM ``Registry`` WHERE ``Key`` LIKE/)
    expect(msiValidation).toContain("$_.Values[2] -eq 'URL Protocol'")
    expect(msiValidation).toContain("Software\\Classes\\huali-ai-mascot\\shell\\open\\command")
    expect(msiValidation).toContain("-notmatch '\\[!Path\\].*%1'")
    expect(deployment).toContain("$ProtocolSubKey = 'SOFTWARE\\Classes\\huali-ai-mascot'")
    expect(deployment).toContain("[regex]::Match($command, '^\\s*\"(?<executable>[^\"]+)\"\\s+\"%1\"\\s*$')")
    expect(deployment).toContain('$registeredHash = (Get-FileHash -LiteralPath $registeredExecutablePath -Algorithm SHA256).Hash')
    expect(deployment).toContain('$expectedHash = (Get-FileHash -LiteralPath $ExpectedExecutablePath -Algorithm SHA256).Hash')
    expect(deployment).toContain('Assert-DesktopAuthProtocol -ExpectedExecutablePath $installedExecutablePath')
    expect(deployment).toContain('function Invoke-DesktopAuthProtocolCallbackSmoke')
    expect(deployment).toContain('Start-Process -FilePath $callbackUrl')
    expect(deployment).toContain('HUALI-AI-MASCOT://AUTH-CALLBACK')
    expect(deployment).toContain('$existingProcess = Start-Process -FilePath $ExpectedExecutablePath -PassThru')
    expect(deployment).toContain('smokeNonce=$nonce')
    expect(deployment).toContain('forwardedToRunningInstance')
    expect(deployment).toContain('rendererReceived')
    expect(deployment).toContain("$candidate.rendererOutcome -eq 'success'")
    expect(deployment).toContain('$candidate.sessionCommitted -eq $true')
    expect(deployment).toContain('$candidate.subscriptionsStarted -eq $true')
    expect(deployment).toContain('$candidate.reminderTypesQueued -eq 3')
    expect(deployment).toContain('$candidate.notificationWindowShown -eq $true')
    expect(deployment).toContain('$restartReceipt.sessionRestoredAfterRestart -eq $true')
    expect(deployment).toContain('singleInstancePreserved = $true')
    expect(deployment).toContain('$report.checks.desktopAuthProtocolCallback = Invoke-DesktopAuthProtocolCallbackSmoke `')
    expect(deployment).toContain('[switch]$RequireRawAuthDiagnostics')
    expect(deployment).toContain('[switch]$RequireDiagnosticLogCleanup')
    expect(deployment).toContain('[switch]$DiagnosticOnly')
    expect(deployment).toContain('-RequireRawDiagnostics:$RequireRawAuthDiagnostics')
    expect(deployment).toContain('-DiagnosticOnly:$DiagnosticOnly')
    expect(deployment).toContain('HUALI-AI-MASCOT://AUTH-CALLBACK/?state=')
    expect(deployment).toContain('New-DesktopDiagnosticCleanupFixture')
    expect(deployment).toContain('Assert-DesktopDiagnosticCleanup -Fixture $diagnosticCleanupFixture')
    expect(deployment).toContain('newDiagnosticLogNotCreated = $true')
    expect(deployment).toContain("$_.Contains('\"event\":\"auth.callback.renderer_parsed\"')")
    expect(deployment).toContain("$_.Contains('\"outcome\":\"success\"')")
    expect(deployment.match(/ConvertFrom-Json -AsHashtable/g)).toHaveLength(3)
    expect(deployment).toContain("[string]$nativeFields['callbackUrl'] -notin @('', '[redacted]')")
    expect(deployment).toContain("$nativeFields['callbackUrlLength'] -eq ([string]$nativeFields['callbackUrl']).Length")
    expect(deployment).toContain("[string]$rendererFields['rawUrl'] -notin @('', '[redacted]')")
    expect(deployment).toContain("$rendererFields['rawUrlLength'] -eq ([string]$rendererFields['rawUrl']).Length")
    expect(deployment).toContain("$_.Contains('\"token\":\"smoke-token\"')")
    expect(deployment).toContain("$rendererFields['receivedState'] -eq $authState")
    expect(deployment).toContain("$rendererFields['expectedState'] -eq $authState")
    expect(deployment).toContain("$rendererFields['stateMatches'] -eq $true")
    expect(deployment).toContain('tokenValueRecorded = $rawDiagnosticsVerified')
    expect(deployment).toContain('completeCallbackUrlRecorded = $rawDiagnosticsVerified')
    expect(deployment).toContain('expectedAndReceivedStateRecorded = $rawDiagnosticsVerified')
    expect(deployment).toContain('Assert-NoDesktopAuthProtocol -Stage $Stage')

    const nativeMain = rustSource.replace(/\r\n?/g, '\n')
    expect(nativeMain).toContain('desktop_auth_callback_query_value(callback_url, "smokeNonce")')
    expect(nativeMain).toContain('"hasState".to_owned()')
    expect(nativeMain).toContain('"hasToken".to_owned()')
    expect(nativeMain).toContain('"hasUserId".to_owned()')
    expect(nativeMain).toContain('"forwardedToRunningInstance".to_owned()')
    expect(nativeMain).toContain('"rendererReceived".to_owned()')
    expect(nativeMain).toContain('record_desktop_auth_renderer_receipt')
    expect(nativeMain).toContain('record_desktop_release_smoke_session')
    expect(nativeMain).toContain('record_desktop_release_smoke_restart')
    expect(nativeMain).toContain('DESKTOP_RELEASE_SMOKE_ENABLED_ENV')
    expect(nativeMain).toContain('"notificationWindowShown": true')
    expect(nativeMain).toContain('Receipt is not authentication')
    expect(nativeMain).not.toMatch(
      /if let Some\(callback_url\) = single_instance_desktop_auth\.capture[\s\S]{0,700}hide_mascot_system_notification_native_window\(app\)/
    )
    expect(nativeMain).toContain('"callbackUrl": callback_url')
    expect(nativeMain).toContain('"callbackUrlUtf8Hex": callback_url_utf8_hex')
    expect(nativeMain).toContain('"state": desktop_auth_callback_query_value(callback_url, "state")')
    expect(nativeMain).toContain('"token": desktop_auth_callback_query_value(callback_url, "token")')
  })

  it('keeps zero, one and many PowerShell results array-shaped under StrictMode', () => {
    const normalized = deploymentSmokeSource.replace(/\r\n?/g, '\n')

    expect(normalized).toContain('@(Get-HualiProcesses).Count -gt 0')
    expect(normalized.match(/\$processes\s*=\s*@\(Get-HualiProcesses\)/g)).toHaveLength(1)
    expect(normalized.match(/\$products\s*=\s*@\(Get-InstalledProducts\)/g)).toHaveLength(2)
    expect(normalized.match(/\$interactiveSessions\s*=\s*@\(Get-InteractiveExplorerSessions\)/g)).toHaveLength(1)
    expect(normalized.match(/\$visualInteractiveSessions\s*=\s*@\(Get-InteractiveExplorerSessions\)/g)).toHaveLength(1)
    expect(normalized.match(/\$finalProducts\s*=\s*@\(Get-InstalledProducts\)/g)).toHaveLength(1)

    expect(normalized).not.toMatch(
      /(?<!@)\(Get-(?:InstalledProducts|HualiProcesses|InteractiveExplorerSessions)\)\.Count/
    )
  })

  it('tells administrators that v1.0.52 removes only legacy diagnostic JSONL files', () => {
    expect(deploymentReadmeSource).toContain('v1.0.52 为正式版')
    expect(deploymentReadmeSource).toContain('存在才删除')
    expect(deploymentReadmeSource).toContain('desktop-diagnostic.jsonl')
    expect(deploymentReadmeSource).toContain('desktop-diagnostic.jsonl.1')
    expect(deploymentReadmeSource).toContain('不删除日志目录')
    expect(deploymentReadmeSource).toContain('后续启动不会重新生成这两个文件')
  })

  it('uses isolated programmatic WebView2 options only for the visual child process', () => {
    const normalized = visualSmokeSource.replace(/\r\n?/g, '\n')

    expect(normalized).toContain("mode = 'programmatic-webview2-options'")
    expect(normalized).toContain('requested = $false')
    expect(normalized).toContain('isolatedDataDirectoryConfigured = $false')
    expect(normalized).toContain('isolatedDataDirectoryRemoved = $false')
    expect(normalized).toContain('animationProgressionObserved = $false')
    expect(normalized).toContain('$report.motionValidation.animationProgressionObserved = $true')
    expect(normalized).toContain("'HUALI_AI_VISUAL_SMOKE_FORCE_MOTION'")
    expect(normalized).toContain('$previousVisualSmokeMotion')
    expect(normalized).toMatch(
      /SetEnvironmentVariable\([\s\S]*?'1'[\s\S]*?Start-Process[\s\S]*?finally\s*\{[\s\S]*?SetEnvironmentVariable\([\s\S]*?\$previousVisualSmokeMotion/
    )
    expect(normalized.match(/EnvironmentVariableTarget]::Process/g)).toHaveLength(3)
    expect(normalized).toContain('"huali-ai-visual-smoke-$($process.Id)"')
    expect(normalized).toContain('Remove-VisualSmokeDataDirectory -Path $visualSmokeDataDirectory')
    expect(normalized).toContain('$report.motionValidation.isolatedDataDirectoryRemoved = $true')
    expect(normalized).toContain('if ($cleanupFailure)')
    expect(normalized).toContain('Stop-Process -Id $process.Id -Force -ErrorAction Stop')
    expect(normalized).toContain('if (-not $process.WaitForExit(5000))')
    expect(normalized).toContain('if (-not $process.HasExited)')
    expect(normalized).not.toContain('WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS')
    expect(normalized).not.toContain('--force-prefers-no-reduced-motion')

    const nativeMain = rustSource.replace(/\r\n?/g, '\n')
    expect(nativeMain).toContain('std::env::var("HUALI_AI_VISUAL_SMOKE_FORCE_MOTION")')
    expect(nativeMain).toMatch(/\.as_deref\(\),\s*Ok\("1"\)/)
    expect(nativeMain).toContain('--force-prefers-no-reduced-motion')
    expect(nativeMain).toContain('--disable-features=msWebOOUI,msPdfOOUI,msSmartScreenProtection')
    expect(nativeMain).toContain('--autoplay-policy=no-user-gesture-required')
    expect(nativeMain).toContain('window.additional_browser_args = Some(')
    expect(nativeMain).toContain('window.create = false')
    expect(nativeMain).toContain('WebviewWindowBuilder::from_config(')
    expect(nativeMain).toContain('.data_directory(visual_smoke_data_directory.clone())')
    expect(nativeMain).not.toContain('window.data_directory = Some(')
    expect(nativeMain).toContain('huali-ai-visual-smoke-{}')
    expect(nativeMain).toContain('.build(context)')
    expect(nativeMain).toContain('.run(|app, event|')
    expect(nativeMain).not.toContain('.run(tauri::generate_context!())')
  })
})
